services:
  immich-public-proxy:
    # image: alangrainger/immich-public-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: immich-public-proxy
    restart: always
    ports:
      - "3000:3000"
    environment:
      PUBLIC_BASE_URL: http://localhost:3000
      IMMICH_URL: https://photos.home.bartho.dev
